---
- name: Create and Delete VLANs on MikroTik Router
  hosts: all
  gather_facts: no
  tasks:
    - name: Create VLAN
      routeros_command:
        commands:
          - "/interface vlan add name=VLAN100 vlan-id=100 interface=ether1"
      register: create_vlan
      ignore_errors: yes

