- name: Test kết nối tới Juniper Switch
  hosts: juniper-switch
  gather_facts: no

  tasks:
    - name: Lấy thông tin version
      juniper.device.junos_command:
        commands:
          - show version
      register: output

    - name: In kết quả
      debug:
        var: output.stdout_lines
