---
- name: Configure IP address for Ethernet interface
  hosts: all
  gather_facts: false

  vars_prompt:
    - name: interface
      prompt: "Enter the interface name (e.g., ether1)"
      private: no

    - name: ip_address
      prompt: "Enter the new IP address (e.g., 192.168.0.2/24)"
      private: no

  tasks:
    - name: Configure interface
      routeros_command:
        commands:
          - "/interface ethernet set [find name='{{ interface }}']"
        host: your_routeros_host
        username: admin
        password: admin

    - name: Add IP address
      routeros_command:
        commands:
          - "/ip address add address='{{ ip_address }}' interface='{{ interface }}'"
        host: your_routeros_host
        username: admin
        password: admin

