---
- name: Disable Ethernet 2 on MikroTik
  hosts: all

  tasks:
    - name: Disable Ethernet 2
      routeros_command:
        commands:
          - "/interface ethernet disable [find name=\"ether2\"]"
