---
- name: Enable Ethernet 2 on MikroTik
  hosts: all

  tasks:
    - name: Enable Ethernet 2
      routeros_command:
        commands:
          - "/interface ethernet enable [find name=\"ether2\"]"
