---
- name: Set IP for Ethernet Interface on MikroTik
  hosts: all
  vars_prompt:
    - name: target_interface
      prompt: "Enter target interface name:"
    - name: target_ip
      prompt: "Enter target IP address (e.g., 192.168.1.2/24):"

  tasks:
    - name: Set IP for target interface
      routeros_command:
        commands:
          - "/interface ethernet set [find name=\"{{ target_interface }}\"]"
          - "/ip address add address=\"{{ target_ip }}\" interface={{ target_interface }}"
